name: Test Using Mocha with PostgreSQL

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fish_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use the appropriate Node.js version

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/fish_db
        run: yarn test
